### ISSUE TITLE
[MINOR] Code improve

### ISSUE THREAD

**Issue by ale1313** [Alexander-Lancellott/Challenge-Nextdots-2020#2]
Directamente podes hacer val.trim().length, sin embargo, que pasa si el user quiere ingresar una bebida que tiene un espacio?

https://github.com/Alexander-Lancellott/Challenge-Nextdots-2020/blob/de3b9b244dfd59137a2e48e8d775eb0f1ed2f168/src/screens/main/cocktailsList/CocktailsList.tsx#L47

**Comment by Alexander-Lancellott** [comment]
no le deja ingresar espacios atrás y adelante, entre medio si
