### ISSUE TITLE
[critical] - Guardar en el reducer sólo los datos que se necesitan

### ISSUE THREAD

**Issue by edgarbonillag** [Alexander-Lancellott/Challenge-Nextdots-2020#5]
Estoy viendo que de la API llega un objeto, y dentro llega un objeto `drinks` que es un array.
Idealmente en el reducer sólo deberías guardar un array donde cada objeto sea un cocktail con sólo los datos que necesitas.

Eso lo puedes hacer tomando el `data.drinks` y haciendo un map y retornando por cada iteración un objeto con sólo la información necesaria para que se guarde en el reducer. Y dentro del reducer hacer algo que referenciaré en otro issue.

https://github.com/Alexander-Lancellott/Challenge-Nextdots-2020/blob/4ee59e85911184076fea2e464bc003a602519ca0/src/actions/getCocktails.ts#L19

**Comment by Alexander-Lancellott** [comment]
De esta forma está  bien ?
